---

mysql_community_repository: >-
  https://mirrors.ustc.edu.cn/mysql-repo/mysql57-community-release-el7-9.noarch.rpm

# Debian 9
debian_apt_repository: >-
  deb https://mirrors.tuna.tsinghua.edu.cn/mysql/apt/debian/ 
  {{ ansible_distribution_release }} mysql-5.7
  