---

- name: install c compiler
  yum: 
    name: gcc 
    state: present
    update_cache: yes

- name: install c++ compiler
  yum: 
    name: gcc-c++
    state: present

- name: install make
  yum: 
    name: make
    state: present

# perl 5 openssl 需要
- name: install perl 
  yum: 
    name: perl
    state: present