---

- name: mkdir nginx_confd_path
  file:
    path: "{{ nginx_path }}/conf/conf.d"
    state: directory

- name: add nginx.conf
  template: 
    src: nginx.conf.j2
    dest: "{{ nginx_path }}/conf/nginx.conf"

- name: add conf.d/default_server.conf
  template: 
    src: default_server.conf.j2
    dest: "{{ nginx_path }}/conf/conf.d/default_server.conf"

