---

- name: include vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: define nginx_user
  set_fact: 
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

- name: define nginx_group
  set_fact: 
    nginx_group: "{{ __nginx_group }}"
  when: nginx_group is not defined

- name: install c and c++ compiler
  include_tasks: "{{ ansible_os_family }}-dependent-software.yml"

- name: unarchive files
  include_tasks: unarchive-file.yml

- name: compiler nginx
  include_tasks: compiler-nginx.yml

- name: config nginx
  include_tasks: config-nginx.yml

- name: systemd nginx.service
  include_tasks: systemd.yml
  
