---

- name: include vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: define nginx_user
  set_fact: 
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

- name: define nginx_group
  set_fact: 
    nginx_group: "{{ __nginx_group }}"
  when: nginx_group is not defined

- name: install dependent sofeware
  include_tasks: "dependent-software.yml"

- name: unarchive install file
  include_tasks: unarchive-file.yml

- name: compiler nginx
  include_tasks: compiler-nginx.yml

- name: configure nginx
  include_tasks: config-nginx.yml

- name: start nginx
  include_tasks: systemd.yml
  