---

- name: include vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: install c and c++ compiler
  include_tasks: "{{ ansible_os_family }}-dependent-software.yml"

- name: unarchive files
  include_tasks: unarchive-file.yml

- name: compiler nginx
  include_tasks: compiler-nginx.yml

- name: config nginx
  include_tasks: config-nginx.yml

- name: systemd nginx.service
  include_tasks: systemd.yml
  
