---

- name: CentOS <jemalloc> error
  shell: cd /tmp/redis-stable/deps && \
    make hiredis lua jemalloc linenoise
  when: ansible_os_family == "RedHat"

- name: start compile && install redis
  shell: cd /tmp/redis-stable && \
    make && make install 
  register: result

- name: delete redis directory
  file: 
    path: /tmp/redis-stable
    state: absent
  when: result.rc == 0