---

- name: install aria2 from source
  apt: 
    name: aria2
    state: present
    update_cache: yes

- name: mkdir aria2 directory and storage path
  file: 
    path: "{{ item }}"
    state: directory
    owner: nobody
    group: nogroup
  with_items: 
    - "/usr/local/aria2"
    - "{{ aria2_dir }}"

- name: touch session and dht file
  file: 
    path: "{{ item }}"
    state: touch
    owner: nobody
    group: nogroup
  with_items: 
    - "{{ aria2_input_file }}"
    - "{{ aria2_save_session }}"
    - "{{ aria2_dht_file_path }}"

- name: copy configure
  template: 
    src: aria2.conf.j2
    dest: /usr/local/aria2/aria2.conf
    owner: nobody
    group: nogroup

# 打开防火墙端口
- name: firewall accept port
  iptables: 
    action: insert
    chain: INPUT
    protocol: "{{ item.proto }}"
    destination_port: "{{ item.port }}"
    jump: ACCEPT
  with_items: 
    - {port: "{{ aria2_rpc_listen_port }}", proto: "tcp"}
    - {port: "{{ aria2_listen_port.split('-')|join(':') }}", proto: "tcp"}
    - {port: "{{ aria2_listen_port.split('-')|join(':') }}", proto: "udp"}
    - {port: "{{ aria2_dht_listen_port.split('-')|join(':') }}", proto: "tcp"}
    - {port: "{{ aria2_dht_listen_port.split('-')|join(':') }}", proto: "udp"}

- name: copy aria2.service
  template: 
    src: aria2.service.j2
    dest: /lib/systemd/system/aria2.service
  notify: systemctl start aria2
