---

tmp_path: "/tmp/nginx-compile"
nginx_path: "/usr/local/nginx"

nginx_gzip: "on"
nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"
nginx_server_tokens: "off"

nginx_keepalive_timeout: "60"

nginx_pid_path: "{{ nginx_path }}/logs/nginx.pid"
nginx_error_log: "{{ nginx_path }}/logs/error.log"
nginx_access_log: "{{ nginx_path }}/logs/access.log"
nginx_log_format: |-
    '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"'

nginx_worker_connections: "1024"
nginx_worker_processes: >-
  "{{ ansible_processor_vcpus | default(ansible_processor_count) }}"

nginx_extra_conf_options: |
  include {{ nginx_path }}/conf/conf.d/*.conf;

nginx_vhost: 
  - listen: "80"
    server_name: "{{ ansible_default_ipv4.address }}"
    root: "{{ nginx_path }}/html"
    index: "index.html index.htm"
    error_page: "500 502 503 504  /50x.html"
    access_log: "{{ server_name|default(ansible_default_ipv4.address) }}.access.log"
    error_log: "{{ server_name|default(ansible_default_ipv4.address) }}.error.log"

nginx_configure_parameter: "--prefix={{ nginx_path }} \
    --user={{ __nginx_user }} --group={{ __nginx_group }} \
    --with-http_v2_module --with-http_ssl_module --with-stream \
    --with-stream_ssl_module --with-http_sub_module \
    --with-http_realip_module --with-stream_realip_module \
    --with-zlib=../{{ zlib_archive_name }} \
    --with-pcre=../{{ pcre_archive_name }} \
    --with-openssl=../openssl-{{openssl_archive_name}}"
