--- 

# 移除mariadb等包
- name: remove mariadb
  apt: 
    name: "mariadb*"
    state: absent

- name: install apt-transport-https
  apt: 
    name: apt-transport-https

- name: add mysql key
  apt_key: 
    keyserver: keyserver.ubuntu.com 
    id: 8C718D3B5072E1F5

- name: add mysql repository
  apt_repository:
    repo: "{{ debian_apt_repository }}"
