---

- name: ensure data path is exist
  file: 
    path: "{{ mysql_path }}"
    state: directory
    owner: mysql
    group: mysql
    mode: 0700

- name: ensure binlog path is exist
  file: 
    path: "{{ mysql_binlog_path }}"
    state: directory
    owner: mysql
    group: mysql
    mode: 0700

- name: ensure error log is exist
  file: 
    path: "{{ mysql_log_path }}/mysqld.log"
    state: touch
    owner: mysql
    group: mysql
    mode: 0644

- name: ensure pid path is exist
  file: 
    path: "{{ mysql_pid_path }}"
    state: directory


- name: disable selinux
  selinux: 
    policy: targeted
    state: permissive
  when: ansible_os_family == "RedHat"
