---

- name: remove old docker 
  yum: 
    name: 
      - docker 
      - docker-io
      - docker-engine
      - containerd 
      - runc 
    state: absent


- name: install required packages
  yum: 
    name: 
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - gnupg2 
      - software-properties-common 
    state: present
    

- name: add docker key
  apt_key: 
    url: "{{ apt_key_url }}"
    state: present

- name: add repository
  apt_repository: 
    repo: "{{ apt_repository }}"
    filename: docker-ce
    