---

- name: remove old docker 
  yum: 
    name: 
      - docker 
      - docker-client 
      - docker-client-latest 
      - docker-common 
      - docker-latest 
      - docker-latest-logrotate 
      - docker-logrotate 
      - docker-engine
    state: absent
    
- name: install required packages
  yum: 
    name: 
      - yum-utils
      - device-mapper-persistent-data
      - lvm2 

- name: get repository
  get_url: 
    url: "{{ yum_repository_url }}"
    dest: "/etc/yum.repos.d/docker-ce.repo"
    mode: 0644
